# Práctica 1

In [21]:
import matplotlib.pyplot as plt
import numpy as np

In [22]:
def logistica(x):
    return R*x*(1-x)
    
def orbita(x0, f, n):
    orb = np.empty([n])
    orb[0] = f(x0)
    for i in range(n - 1):
        orb[i + 1] = f(orb[i])
    return orb

def tiempo_transitorio(orb, epsilon=0.001):
    m = 0
    next_sup, next_inf = max(orb[m + N : m + 2 * N]), min(orb[m + N : m + 2 * N])
    while m+N <= N0:
        sup, inf = max(orb[m : m + N]), min(orb[m : m + N])
        if abs((sup - inf) - (next_sup - next_inf)) < epsilon:
            return m
        m =+ N
        next_sup, next_inf = sup, inf
    return N0
    
def periodo(suborb, epsilon=0.001):
    n = len(suborb)
    for i in range(1, n):
        if abs(suborb[n - 1] - suborb[n - i - 1]) < epsilon:
            return i
    return n

def atrac(x0, f, epsilon=0.001):
    orb = orbita(x0, f, N0)
    m = tiempo_transitorio(orb, epsilon)
    suborb = orb[-m:]
    p = periodo(suborb, epsilon)
    v0 = np.sort(suborb[-p:])
    return v0

In [23]:
eps = 0.001

N0 = 200  # nuestra capacidad de cómputo máxima
N = 50  # sabemos de antemano que nuestro conjunto será menor que esto

## Apartado i)

In [24]:
def equals(v1,v2, epsilon=0.001):
    for i,j in zip(v1,v2):
        if abs(i-j) >= epsilon:
            return False
    return True
    
def test_V0(v0, epsilon=0.001):
    global R
    r = R
    print(v0)

    for x0 in np.arange(epsilon,1,epsilon):
        v1 = atrac(x0, logistica, epsilon)
        if not equals(v0,v1,epsilon):
            print("X0",x0,"not stable")

    for delta in np.arange(epsilon,1,epsilon):
        R = r+delta
        v1 = atrac(0.2, logistica, epsilon)
        if not equals(v0,v1,epsilon):
            print("R",R,"is different")
            print("\t",v0)
            print("\t",v1)
            break
    
    for delta in np.arange(epsilon,1,epsilon):
        R = r-delta
        v1 = atrac(0.2, logistica, epsilon)
        if not equals(v0,v1,epsilon):
            print("R",R,"is different")
            print("\t",v0)
            print("\t",v1)
            break
    R = r

In [25]:
R = 3.14
v0 = atrac(0.2, logistica, eps)
test_V0(v0, eps)

[0.53800722 0.78046412]
R 3.1430000000000002 is different
	 [0.53800722 0.78046412]
	 [0.53663584 0.78153151]
R 3.137 is different
	 [0.53800722 0.78046412]
	 [0.53939423 0.77938167]


In [26]:
R = 3.5
v0 = atrac(0.2, logistica, eps)
test_V0(v0, eps)

[0.38281968 0.50088421 0.82694071 0.87499726]
R 3.502 is different
	 [0.38281968 0.50088421 0.82694071 0.87499726]
	 [0.38175748 0.50209314 0.82653751 0.87548466]
R 3.498 is different
	 [0.38281968 0.50088421 0.82694071 0.87499726]
	 [0.38390574 0.49965119 0.82735439 0.87449957]


## Apartado ii)

In [27]:
R = 3.544

for r in np.arange(3.544,4,eps):
    R = r
    v0 = atrac(0.2, logistica, eps)

    if len(v0) == 8:
        test = True
        v1 = atrac(0.2+eps, logistica, eps)
        if not equals(v0,v1,eps):
            test = False
        v1 = atrac(0.2-eps, logistica, eps)
        if not equals(v0,v1,eps):
            test = False
        if test:
            print("R",R,"\t",v0)

R 3.5479999999999996 	 [0.35647172 0.36914795 0.50935376 0.53738213 0.8139099  0.82625023
 0.88204194 0.88668958]
R 3.5489999999999995 	 [0.35559752 0.3697755  0.5076091  0.53901131 0.81324598 0.82706457
 0.88184884 0.88704452]
R 3.5499999999999994 	 [0.35480045 0.37032556 0.50603051 0.54047483 0.81265567 0.82780512
 0.88168435 0.8873709 ]
R 3.5509999999999993 	 [0.35406177 0.37081688 0.50457711 0.54181346 0.81212092 0.82848992
 0.88154155 0.88767561]
R 3.551999999999999 	 [0.35336938 0.37126157 0.50322259 0.54305351 0.81163009 0.82913063
 0.881416   0.88796311]
R 3.552999999999999 	 [0.35271489 0.37166804 0.50194874 0.54421319 0.81117511 0.82973531
 0.88130457 0.88823651]
R 3.553999999999999 	 [0.35209219 0.37204237 0.50074235 0.54530569 0.81075014 0.83030981
 0.88120504 0.88849804]
R 3.554999999999999 	 [0.35149669 0.37238919 0.4995935  0.54634095 0.81035076 0.83085853
 0.8811157  0.88874941]
R 3.5559999999999987 	 [0.35092482 0.37271206 0.49849446 0.54732669 0.80997356 0.8313849
 0.